### ISSUE TITLE
differentiation from gulp-batch

### ISSUE THREAD

**Issue by laurelnaiad** [andresberrios/gulp-aggregate#1]
Hi --

Thanks for sharing this. I'm trying to understand how this differs from gulp-batch.

I think your readme is indicating that gulp-aggregate dedupes on the file paths it sees during the debounce period (something I don't know that gulp-batch does??)?

**Comment by andresberrios** [comment]
Hi! Sorry for the delay, these last couple of days have been a bit busy.

You're right. I don't know whether

**Comment by andresberrios** [comment]
Hi! Sorry for the delay, these last couple of days have been a bit busy.

You're right. I don't know whether `gulp-batch` dedupes file paths, but `gulp-aggregate` does, as it buffers only the last version of each file, and in fact keeps them (and sends them through to the new stream in the callback) in the same order in which they were originally received, in order to maintain consistency.

The important difference is something else, though. I created this module even if at the time `gulp-batch` was available because `gulp-batch` only sent the files that were changed in that debounced period to the new stream in the callback. I needed something similar but with all the files that had been received by this stream, since the start of the process, with the recently changed ones updated. So, the callback will be triggered in much the same way as in `gulp-batch`, but the stream you receive will send all the files that have ever passed through here, with contents up to date.

This was necessary for using other modules that expect both the stream to `end`, and the stream to send all the files, like a Gulp build process that doesn't `watch`, since `watch` only sends the changed files. An example of such a kind of module would be `gulp-concat`. There were several others, but I can't remember right now. I've been mostly using Meteor and Rails for a long time, and I really love not having to worry much about the build process, although it was interesting to design it and code it by hand using streams.

I hope the explanation helps! Let me know if you have any further questions.
Btw, happy holidays! :D

**Comment by laurelnaiad** [comment]
Thank you for your response, and happy holidays, to you, as well.

After I asked the question, I looked far enough to partially realize what you described. I also realized that neither this nor gulp-batch were doing what I needed, which was more of a straight "flush/end debouncer" for gulp-watch.

Something like:

```
/**
 * Passthrough stream to pipe files into a stream returned by streamLambda
 * until the debouncePeriod ends. When the debouncePeriod ends, ends
 * the stream returned by streamLambda, and prepares itself to be used
 * again when subseuqent files arrive. The endOnDebounced stream
 * does not expect to be ended, but does cause the expected flush/end process
 * to happen on the lambda stream at expiry of the debouncePeriod.
 */
export default function endOnDebounce(
  /**
   * Lambda for a passthrough stream that will be debounced such that
   * it is ended after debouncePeriod expires. A new lambdaStream would/will
   * be created on subsequent file.
   */
  streamLambda: () => NodeJS.ReadWriteStream,
  /**
   * Time (in ms) to wait before concluding there will be no more files, and
   * thus ending the created stream.
   */
  debouncePeriod: number
) {
  var debounce = require('debounce');
  var through = require('through2');
  var myStream;
  var debouncer = through.obj(function (file, enc, cb) {
    if (!myStream) {
      myStream = streamLambda();
      myStream.db = debounce(function () {
        myStream.end();
        myStream = undefined;
      }, debouncePeriod);
    }
    myStream.write(file);
    myStream.db();
    cb();
  });
  return debouncer;
}

  // demo's the debounceWatch function
  var getWatchStreamProcess = function () {
    return through.obj(function (file, enc, cb) {
      console.log(file.path);
      this.push(file);
      cb();
    }, function (cb) {
      console.log('flush');
      cb();
    });
  };

  watch([myGlob, specs.projectGlob], {
    base: process.cwd()
  }).pipe(endOnDebounce(getWatchStreamProcess, 500));
```

The difference may be as simple as where you hold onto files and resend them -- I just want the fresh files... i.e. the I need the flush/end events that gulp-watch doesn't provide, but not the aggregation over the process lifetime.... so a different use case. (P.S. Nobody copy that code above! I just wrote it shortly after waking up to explain what I was seeking -- it's ugly and probably has bugs.)
